

services:
  discord-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: discord-bot-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - discord-bot-dev-network

networks:
  discord-bot-dev-network:
    driver: bridge
