

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
